### PR TITLE
fix: Fix incorrect routes for multiple networks

### LINKED ISSUE #53: multus network with bridge cni plugins
Hello

I'm trying to use multus with bridge cni plugin: 

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: overlay
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "overlay",
    "type": "bridge",
    "bridge": "my-bridge",
    "ipam": {
        "type": "host-local",
        "subnet": "10.88.0.0/16"
    }
  }'

---
apiVersion: virt.virtink.smartx.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ubuntu-rootfs
spec:
  instance:
    cpu:
      sockets: 4
      coresPerSocket: 1
    memory:
      size: 4Gi
    kernel:
      image: smartxworks/virtink-kernel-5.15.12
      imagePullPolicy: IfNotPresent
      cmdline: "console=ttyS0 root=/dev/vda rw"
    disks:
      - name: ubuntu
      - name: cloud-init
    interfaces:
      - name: pod
        bridge: {}
      - name: overlay
        bridge: {}
  networks:
    - name: pod
      pod: {}
    - name: overlay
      multus:
        networkName: overlay
  volumes:
    - name: ubuntu
      containerRootfs:
        image: smartxworks/virtink-container-rootfs-ubuntu
        imagePullPolicy: IfNotPresent
        size: 16Gi
    - name: cloud-init
      cloudInit:
        userData: |-
          #cloud-config
          password: password
          chpasswd: { expire: False }
          ssh_pwauth: True
```

and got vm failed:

```console
% k get vm
NAME            STATUS   NODE
ubuntu-rootfs   Failed   
```

there is no any logs (and Pod with VM also destroyed) but I've catch related logs:

```console
2022/09/15 08:54:05 Failed to build VM config: setup bridge network: start DHCP server: start dnsmasq: "/usr/sbin/dnsmasq --conf-file=/var/run/virtink/dnsmasq/br-net1.conf --pid-file=/var/run/virtink/dnsmasq/br-net1.pid": exit status 1: 
dnsmasq: bad IP address at line 6 of /var/run/virtink/dnsmasq/br-net1.conf
```
As I understand on line 6 ether is router details usually (`dhcp-option=option:router`)

VM started only when bridge has setting `IsDefaultGateway: true`:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: overlay
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "overlay",
    "type": "bridge",
    "bridge": "my-bridge",
    "isDefaultGateway": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.88.0.0/16"
    }
  }'
```
but then networking inside pod with vm looks weird and pod not available via net

### PR DESCRIPTION
**Pull request by scuzhanglei**
Fix generate cloud-init network-config error
fix #53

### CODE REVIEW

File: cmd/virt-prerunner/main.go [hunk 1]
```diff
@@ -503,10 +510,15 @@ func startDHCPServer(ifaceName string, mac net.HardwareAddr, ipNet *net.IPNet, g
 		"mac":          mac.String(),
 		"ip":           ipNet.IP.String(),
 		"mask":         net.IP(ipNet.Mask).String(),
-		"gateway":      gateway.String(),
+		"routes":       formatAndSortRoutes(routes),
 		"dnsServer":    strings.Join(resolvconf.GetNameservers(rc.Content, types.IPv4), ","),
 		"domainSearch": strings.Join(resolvconf.GetSearchDomains(rc.Content), ","),
 	}
+
+	if !gateway.Equal(nil) {
```
Comment (fengye87) [inline cmd/virt-prerunner/main.go:518]: Why not `gateway != nil`?

File: cmd/virt-prerunner/main.go [hunk 2]
```diff
@@ -503,10 +510,15 @@ func startDHCPServer(ifaceName string, mac net.HardwareAddr, ipNet *net.IPNet, g
 		"mac":          mac.String(),
 		"ip":           ipNet.IP.String(),
 		"mask":         net.IP(ipNet.Mask).String(),
-		"gateway":      gateway.String(),
+		"routes":       formatAndSortRoutes(routes),
```
Comment (fengye87) [inline cmd/virt-prerunner/main.go:513]: If routes is an empty array, the result would be an empty string? Is it expected?

File: cmd/virt-prerunner/main.go (hunk 1 above)
Comment (scuzhanglei) [reply cmd/virt-prerunner/main.go:518]: `Equal(nil)` can handle nil and empty.

Comment (fengye87) [reply cmd/virt-prerunner/main.go:518]: So can `len(gateway) != 0`? It's a bit counter-intuitive to do `gateway.Equal(nil)` if gateway can be nil

File: cmd/virt-prerunner/main.go (hunk 2 above)
Comment (scuzhanglei) [reply cmd/virt-prerunner/main.go:513]: a pod interface with IPAM enable, it will at least have one route. If IPAM disabled will not start a dhcp server. to make it robust, I just test with  empty routes, the dhcp server still works with `dhcp-option=option:classless-static-route,`

**Review by fengye87 — APPROVED** [review]
